### PR TITLE
Added missing parts to the `CMakeLists.txt` code.

### PR DESCRIPTION
**Pull request by jrutgeer**
As of yet, copy-paste of the tutorial code does not compile.

First error message:

```
get_target_property() called with non-existent target "gz-msgs::gz-msgs"
```
This is due to `${GZ_MSGS_VER}` not being set.

After rectifying this, another error results:
```
Missing input file.
```
This is due to `${MSGS_PROTOS}` not being set.

This PR adds these variable definitions to the example code, and also some extra documentation on the use of the `${GZ_MSGS_VER}` variable.

### CODE REVIEW

**Comment by mjcarroll** [comment]
Thanks, this should reflect https://github.com/gazebosim/gz-msgs/blob/gz-msgs10/examples/generating_custom_msgs/CMakeLists.txt, but it maybe got out of sync at some point.

**Comment by azeey** [comment]
Added `CMakeLists.txt` to https://github.com/gazebosim/gz-cmake/issues/387. Once that's resolved, we should be able to use `\snippet` instead of copying example code in the tutorial.

**Comment by jrutgeer** [comment]
> Thanks, this should reflect https://github.com/gazebosim/gz-msgs/blob/gz-msgs10/examples/generating_custom_msgs/CMakeLists.txt, but it maybe got out of sync at some point.

Ok, in hindsight that is obvious, but I didn't realise there was an 'examples' folder. I've added a reference to the tutorial so the reader knows where to find the code.

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
@jrutgeer looks like one minor doctest issue here:

```
/github/workspace/tutorials/message_generation.md:124: warning: Illegal </br> tag found
```

**Comment by jrutgeer** [comment]
@mjcarroll removed the \</br\>

**Pull request merged**
