### PR TITLE
Harmonic: TODOs related with the migration from `ign` to `gz`

### PR DESCRIPTION
**Pull request by ahcorde**
# 🎉 New feature

## Summary
TODOS related with the migration from `ign` to `gz`

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by nkoenig — APPROVED** [review]

**Comment by azeey** [comment]
Can you resolve conflicts?

**Comment by iche033** [comment]
looks like the files with conflicts in `src` were removed and the bzl file diff is probably out-of-date so we may not need this PR anymore

**Comment by mjcarroll** [comment]
>  bzl file diff is probably out-of-date

That got dropped here, maybe not picked up in a forward port yet? https://github.com/gazebosim/gz-msgs/pull/347

**Comment by iche033** [comment]
Just merged from `gz-msgs10` and now we have 0 changes :)

**Comment by iche033** [comment]
Closing this PR

**Pull request closed without merging**
