### PR TITLE
Merge gz-msgs9 ➡️  main

### PR DESCRIPTION
**Pull request by scpeters**
# ➡️  Forward port

Port `gz-msgs9 ` ➡️  `main`

Branch comparison: https://github.com/ignitionrobotics/ign-msgs/compare/main...gz-msgs9

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@osrf-jenkins run tests please!

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
@scpeters homebrew build can't find protobuf.

**Comment by scpeters** [comment]
> @scpeters homebrew build can't find protobuf.

it was an issue with the formula that I believe is fixed by https://github.com/osrf/homebrew-simulation/pull/2308

restarting homebrew build...

**Comment by scpeters** [comment]
trying to fix a jammy compiler warning in https://github.com/gazebosim/gz-msgs/pull/351/commits/ccfbba945a45a11de6c55baf8f08a7f8654fcd1e

**Pull request merged**
