### PR TITLE
Added motion duration to gui_camera.proto

### PR DESCRIPTION
**Pull request by jrutgeer**
# 🎉 New feature

## Summary
Added 'duration' field to the proto, to allow to set the duration for the 'move to pose' service of the [camera tracking plugin](https://github.com/gazebosim/gz-gui/tree/gz-gui8/src/plugins/camera_tracking).

### CODE REVIEW

**Comment by azeey** [comment]
This would be a good feature to add, but unfortunately, adding a field to an existing message breaks ABI, therefore this needs to target `main`.

**Comment by jrutgeer** [comment]
> therefore this needs to target main.

Bummer. :-)

I tried to change this, but I did not succeed. Is there some way to retarget just this change, or should I rather close this and make a new PR?

**Comment by azeey** [comment]
Looks like @mjcarroll has changed the base branch on the PR, but you'll need to run `git rebase` to rebase the changes onto `main`

**Comment by ahcorde** [comment]
friendly ping @jrutgeer

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@osrf-jenkins run tests please!

**Pull request merged**
