### PR TITLE
Added cubemap_uri to sky

### PR DESCRIPTION
**Pull request by nkoenig**
# 🎉 New feature

## Summary
Added a `cubemap_uri` string to the `sky.proto` message, which supports https://github.com/gazebosim/sdformat/pull/1037.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
Test failures look to be unrelated.  Any chance you would want to address them here or is this time-critical?

**Comment by mjcarroll** [comment]
Actually, is this supposed to be targeting main or `gz-msgs9`

**Comment by nkoenig** [comment]
This is suppose to target main because msgs9 has already been released. I could squint my eyes and sneak this into `gz-msgs9`. It technically breaks API, but I doubt anyone has used gz-msgs9 in the last couple hours.

**Review by mabelzhang — APPROVED** [review]

**Comment by mabelzhang** [comment]
Test failures look to be unrelated (bash completion flags).
This is time critical for end of the week.

**Comment by mabelzhang** [comment]
Wait, we're doing skybox for Fortress, which is still on msgs8 right?

**Comment by nkoenig** [comment]
This is not needed for the skybox work. The skybox work uses the header map in the sky message. This is here to replace that method in the future.

**Comment by nkoenig** [comment]
Waiting on gz-sim7 to main forward port.

**Pull request merged**
