### PR TITLE
gz_TEST: one more ign -> gz

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Fixes failing test

## Summary

There is a portion of the `UNIT_gz_TEST` that is still calling the `ign` command, but that was removed from gz-tools2, so the test is failing. Just call `gz` instead.

* [Build Status](https://build.osrfoundation.org/job/ignition_msgs-ci-gz-msgs9-focal-amd64/3/) https://build.osrfoundation.org/job/ignition_msgs-ci-gz-msgs9-focal-amd64/3/testReport/(root)/CmdLine/MsgHelpVsCompletionFlags/

~~~
tools/gz_TEST.cc:120
Expected: (std::string::npos) != (helpOutput.find(flag)), actual: 18446744073709551615 vs 18446744073709551615
sh: 1: ign: not found
~~~

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [X] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by scpeters** [comment]
I've also removed the `include/ignition/msgs/test_config.h` redirection header per #302 and a discussion with @methylDragon, which should fix the abi-checker build

**Comment by methylDragon** [comment]
ABI checker is still failing with the same issue. It might be from a dirty workspace, I'm going to clear the workspace and rerun the job.

**Comment by scpeters** [comment]
> ABI checker is still failing with the same issue. It might be from a dirty workspace, I'm going to clear the workspace and rerun the job.

I think the ABI checking is failing on the target branch; I think the job won't succeed until this has been merged to `gz-msgs9`

**Comment by scpeters** [comment]
> > ABI checker is still failing with the same issue. It might be from a dirty workspace, I'm going to clear the workspace and rerun the job.
> 
> I think the ABI checking is failing on the target branch; I think the job won't succeed until this has been merged to `gz-msgs9`

I merged https://github.com/gazebosim/gz-msgs/pull/301/commits/104ea78892cb639d82dbdc60230ac40454d7f244 directly to `gz-msgs9` in #303, so I expect CI to be fixed now

**Comment by scpeters** [comment]
> I merged [104ea78](https://github.com/gazebosim/gz-msgs/commit/104ea78892cb639d82dbdc60230ac40454d7f244) directly to `gz-msgs9` in #303, so I expect CI to be fixed now

and it's fixed!

**Pull request merged**
